@ow_api_HostAddress = http://localhost:5038

POST {{ow_api_HostAddress}}/api/v1/listimport
Accept: application/json
Content-Type: application/json

{
    "name": "Renegade",
    "description": "",
    "game": "the-old-world",
    "points": 2000,
    "army": "dark-elves",
    "characters": [],
    "core": [
        {
            "name_en": "Dark Elf Warriors",
            "name_cn": "黑暗精灵战士",
            "name_de": "Dark Elf Warriors",
            "name_es": "Guerreros elfos oscuros",
            "name_fr": "Guerriers Elfes Noirs",
            "id": "dark-elf-warriors.yunkekl",
            "points": 8,
            "minimum": 10,
            "maximum": 0,
            "command": [
                {
                    "name_en": "Lordling (champion)",
                    "name_cn": "领队(冠军)",
                    "name_de": "Lordling (champion)",
                    "name_es": "Señor (campeón)",
                    "name_fr": "Patricien (champion)",
                    "points": 5,
                    "id": 0,
                    "active": true
                },
                {
                    "name_en": "Standard bearer",
                    "name_cn": "旗手",
                    "name_de": "Standard bearer",
                    "name_es": "Portaestandarte",
                    "name_fr": "Porte-étendard",
                    "points": 5,
                    "magic": {
                        "types": [
                            "banner"
                        ],
                        "maxPoints": 50,
                        "selected": [
                            {
                                "name_cn": "战旗",
                                "name_de": "Kriegsbanner",
                                "name_en": "War Banner",
                                "name_fr": "Bannière de Guerre",
                                "name_it": "Stendardo da Guerra",
                                "name_pl": "Sztandar wojenny",
                                "points": 25,
                                "type": "banner",
                                "onePerArmy": true,
                                "name": "war banner",
                                "id": 43
                            }
                        ]
                    },
                    "notes": {
                        "name_en": "0-1 Dark Elf Warriors or Repeater Crossbowman per 1000 points may purchase a magic standard",
                        "name_cn": "0-1单位/每1000分可以选择装备一个魔法战旗",
                        "name_it": "0-1 Dark Elf Warriors or Repeater Crossbowman per 1000 points may purchase a magic standard",
                        "name_de": "0-1 Einheit pro 1000 Punkte darf eine Magische Standarte erwerben",
                        "name_fr": "0-1 unité par tranche de 1000 points peut acheter une bannière magique",
                        "name_es": "0-1 Guerreros elfos oscuros o Ballesteros cada 1.000 puntos puede adquirir un estandarte mágico"
                    },
                    "id": 1,
                    "active": true
                },
                {
                    "name_en": "Musician",
                    "name_cn": "乐手",
                    "name_de": "Musician",
                    "name_es": "Músico",
                    "name_fr": "Musicien",
                    "points": 5,
                    "id": 2,
                    "active": true
                }
            ],
            "equipment": [
                {
                    "name_en": "Hand weapons",
                    "name_cn": "单手武器",
                    "name_de": "Hand weapons",
                    "name_es": "Arma de mano",
                    "name_fr": "Armes de base",
                    "points": 0,
                    "perModel": true,
                    "active": true,
                    "id": 0
                },
                {
                    "name_en": "Thrusting spears",
                    "name_cn": "刺矛",
                    "name_de": "Thrusting spear",
                    "name_es": "Lanza",
                    "name_fr": "Lances d’infanterie",
                    "points": 1,
                    "perModel": true,
                    "id": 1
                }
            ],
            "armor": [
                {
                    "name_en": "Light armour, Shields",
                    "name_cn": "轻甲, 盾牌",
                    "name_de": "Light armour, Shields",
                    "name_es": "Armadura ligera, Escudos",
                    "name_fr": "Armure légère, Boucliers",
                    "points": 0,
                    "perModel": true,
                    "active": true,
                    "activeDefault": true,
                    "id": 0
                }
            ],
            "options": [
                {
                    "name_en": "Veteran",
                    "name_cn": "老兵",
                    "name_de": "Veteran",
                    "name_es": "Veterano",
                    "name_fr": "Vétérans",
                    "points": 1,
                    "perModel": true,
                    "minimum": 0,
                    "maximum": 0,
                    "notes": {
                        "name_en": "0-1 Dark Elf Warriors or Repeater Crossbowman per 1000 points",
                        "name_cn": "每1000分0-1",
                        "name_de": "0-1 pro 1000 Punkte",
                        "name_es": "0-1 Guerreros elfos oscuros o Ballesteros por cada 1000 puntos",
                        "name_fr": "0-1 par tranche de 1000 points"
                    },
                    "id": 0,
                    "active": true
                }
            ],
            "mounts": [],
            "items": [],
            "lores": [],
            "specialRules": {
                "name_en": "Close Order, Elven Reflexes, Hatred (High Elves), Martial Prowess",
                "name_cn": "紧密阵型, 精灵反应, 仇恨(高等精灵), 精湛武艺",
                "name_de": "Close Order, Elven Reflexes, Hatred (High Elves), Martial Prowess",
                "name_es": "Orden cerrado, Reflejos élficos, Odio (Altos elfos), Destreza marcial",
                "name_fr": "Ordre Serré, Réflexes Elfiques, Haine (Hauts Elfes), Prouesses Martiales"
            },
            "strength": 14,
            "magic": {
                "items": []
            }
        }
    ],
    "special": [],
    "rare": [],
    "mercenaries": [],
    "allies": [],
    "id": "ejdubuv",
    "armyComposition": "de-renegade",
    "compositionRule": "grand-melee-combined-arms"
}

###

POST {{ow_api_HostAddress}}/api/v1/listimport
Accept: application/json
Content-Type: application/json

{
  "game": "the-old-world",
  "characters": [],
  "core": [
    {
      "id": "dark-elf-warriors",
      "name_en": "Dark Elf Warriors",
      "name_de": "Dunkelelfenkrieger",
      "name_fr": "Guerriers Elfes Noirs",
      "name_es": "Guerreros Elfos Oscuros",
      "name_it": "Guerrieri Elfi Oscuri",
      "name_pl": "Wojownicy Mrocznych Elfow",
      "name_cn": "Dark Elf Warriors",
      "points": "nine",
      "minimum": "ten",
      "maximum": 30,
      "maxSignatureSpells": 0
    }
  ],
  "special": [],
  "rare": [],
  "mercenaries": [],
  "allies": []
}

###
